---
development:
  cloud_name: hwy7j4ucj
  api_key: '273915676469567'
  api_secret: WiFBcRMT9zEICFYTvFTS04oba2I
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hwy7j4ucj
  api_key: '273915676469567'
  api_secret: WiFBcRMT9zEICFYTvFTS04oba2I
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hwy7j4ucj
  api_key: '273915676469567'
  api_secret: WiFBcRMT9zEICFYTvFTS04oba2I
  enhance_image_tag: true
  static_file_support: false

